services:
  keycloakdb:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
  keycloakserver:
    image: quay.io/keycloak/keycloak:19.0.1
    depends_on:
      - keycloakdb
    links:
      - "keycloakdb:mysql"
    ports:
      - "8082:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=mysql
      - DB_DATABASE=keycloak
      - DB_ADDR=mysql
      - DB_USER=keycloak
      - DB_PASSWORD=password
    command: start-dev
